version: '3'
services:

  sleek-airflow:

    image: rflow-image:latest

    volumes:

      - ./airflow:/opt/airflow
      - ./data:/opt/airflow/data


    ports:

      - "8080:8080"

    command: airflow standalone